{
 "title": "ECS V2",
 "tags": [
  "Amazon",
  "CloudWatch",
  "ECS"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Origem", "label": "Origem", "query": "cloudwatch" },
   { "name": "Region", "label": "Region" }
  ]
 },
 "panels": [
  {
   "title": "Running Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": { "ClusterName": "*" },
     "metricName": "RunningTaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Pending Tasks Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dimensions": { "ServiceName": "*" },
     "metricName": "PendingTaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Task Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "metricName": "TaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Service Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dimensions": { "ClusterName": "*" },
     "metricName": "ServiceCount",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CPU Unit Utilized by Instance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expression": "stats sum(CpuUtilized) by bin(2m),EC2InstanceId",
     "logGroupNames": [
      "/aws/ecs/containerinsights/nonprod-apps/performance"
     ],
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Logs",
     "region": "$Region",
     "statsGroups": [
      "bin(2m)",
      "EC2InstanceId"
     ]
    }
   ]
  },
  {
   "title": "Memory Utilized by Instance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expression": "stats sum(MemoryUtilized) by bin(2m),EC2InstanceId",
     "logGroupNames": [
      "/aws/ecs/containerinsights/nonprod-apps/performance"
     ],
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Logs",
     "region": "$Region",
     "statsGroups": [
      "bin(2m)",
      "EC2InstanceId"
     ]
    }
   ]
  },
  {
   "title": "CPU Unit Utilized",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expression": "stats avg(CpuUtilized) by bin(2m),ContainerName",
     "logGroupNames": [
      "/aws/ecs/containerinsights/nonprod-apps/performance"
     ],
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Logs",
     "region": "$Region",
     "statsGroups": [
      "bin(2m)",
      "ContainerName"
     ]
    }
   ]
  },
  {
   "title": "CPU Unit Utilized by Task",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expression": "stats avg(CpuUtilized) by bin(2m),TaskId, ContainerName",
     "logGroupNames": [
      "/aws/ecs/containerinsights/nonprod-apps/performance"
     ],
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Logs",
     "region": "$Region",
     "statsGroups": [
      "bin(2m)",
      "TaskId",
      "ContainerName"
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ServiceName": "*" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryMode": "Metrics",
     "region": "$Region",
     "sql": {
      "from": { "property": { "name": "ECS/ContainerInsights", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "ServiceName", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "CpuUtilized", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT AVG(CpuUtilized) FROM \"ECS/ContainerInsights\" GROUP BY ServiceName",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Memory Utilized",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expression": "stats avg(MemoryUtilized) by bin(2m),ContainerName",
     "logGroupNames": [
      "/aws/ecs/containerinsights/nonprod-apps/performance"
     ],
     "namespace": "AWS/ECS",
     "queryMode": "Logs",
     "region": "$Region",
     "statsGroups": [
      "bin(2m)",
      "ContainerName"
     ]
    }
   ]
  },
  {
   "title": "Memory Utilized by TaskId",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expression": "stats avg(MemoryUtilized) by bin(2m),TaskId,ContainerName",
     "logGroupNames": [
      "/aws/ecs/containerinsights/nonprod-apps/performance"
     ],
     "namespace": "AWS/ECS",
     "queryMode": "Logs",
     "region": "$Region",
     "statsGroups": [
      "bin(2m)",
      "TaskId",
      "ContainerName"
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ServiceName": "*" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network Rx Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "metricName": "NetworkRxBytes",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Network Tx Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "metricName": "NetworkTxBytes",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Storage Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "ServiceName": "*" },
     "metricName": "StorageReadBytes",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Storage Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "ServiceName": "*" },
     "metricName": "StorageReadBytes",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  }
 ]
}