{
 "title": "AWS ELB",
 "tags": [
  "Amazon",
  "ALB",
  "CloudWatch"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Origem", "label": "Origem", "query": "cloudwatch" },
   { "name": "Region", "label": "Region", "query": "regions()" }
  ]
 },
 "panels": [
  {
   "title": "Network Load Balance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Flow Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "*" },
     "metricName": "ActiveFlowCount",
     "namespace": "AWS/NetworkELB",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Processed Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "*" },
     "metricName": "ProcessedBytes",
     "namespace": "AWS/NetworkELB",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Healthy Host",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "TargetGroup": "*" },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/NetworkELB",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Unhealthy Host",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "TargetGroup": "*" },
     "metricName": "UnHealthyHostCount",
     "namespace": "AWS/NetworkELB",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Application Load Balance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Count ALB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "*" },
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "HTTP ELB Erro 500 by Target",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "*" },
     "metricName": "HTTPCode_ELB_500_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "HTTP ELB Erro 502 by Target",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "*" },
     "metricName": "HTTPCode_ELB_502_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "HTTP ELB Erro 503 by Target",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 25 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "*" },
     "metricName": "HTTPCode_ELB_503_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "HTTP ELB Erro 504 by Target",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "*" },
     "metricName": "HTTPCode_ELB_504_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "ALB  Response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "*" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Active Connection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "*" },
     "metricName": "ActiveConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Processed Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "*" },
     "metricName": "ProcessedBytes",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Target Group Aplication Load Balance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP Target  2XX by Target",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "dimensions": { "TargetGroup": "*" },
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "HTTP Target Erro 5XX by Target",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "dimensions": { "TargetGroup": "*" },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Request Count Target",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "TargetGroup": "*" },
     "metricName": "RequestCountPerTarget",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Target Response",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "TargetGroup": "*" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Unhelthy Houst Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "TargetGroup": "*" },
     "metricName": "UnHealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  }
 ]
}