{
 "title": "NAT gateway",
 "tags": [
  "Amazon",
  "Cloudwatch",
  "NAT"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Origem", "label": "Origem", "query": "cloudwatch" },
   { "name": "Region", "label": "Region" }
  ]
 },
 "panels": [
  {
   "title": "Active Connection",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "*" },
     "metricName": "ActiveConnectionCount",
     "namespace": "AWS/NATGateway",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Bytes Out To Destination",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "*" },
     "metricName": "BytesOutToDestination",
     "namespace": "AWS/NATGateway",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Bytes In from Destination",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "*" },
     "metricName": "BytesInFromDestination",
     "namespace": "AWS/NATGateway",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Bytes Out to Source",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "*" },
     "metricName": "BytesOutToSource",
     "namespace": "AWS/NATGateway",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Bytes In from Source",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "*" },
     "metricName": "BytesInFromSource",
     "namespace": "AWS/NATGateway",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Erro Port Allocation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "*" },
     "metricName": "ErrorPortAllocation",
     "namespace": "AWS/NATGateway",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Packets Drop",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "*" },
     "metricName": "PacketsDropCount",
     "namespace": "AWS/NATGateway",
     "queryMode": "Metrics",
     "region": "$Region",
     "statistic": "Sum"
    }
   ]
  }
 ]
}