[]
# - name: openapi
#   stages:
#     - name: dev-openapi
#   cors:
#     allowOrigins:
#       - "https://docs.dev.xxxx.com.br"
#     allowMethods:
#       - "GET"
#       - "POST"
#       - "OPTIONS"
#     allowHeaders:
#       - "*"    
#   protocolType: HTTP
#   authorizer:
#     - name: openapi-authorizer
#       sharedAuthorizer: true
#       authorizerPayloadFormatVersion: "2.0"
#       lambdaName: openapi-authorizer
#       authorizerType: REQUEST
#       authorizerUri: arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:111111:function:openapi-authorizer/invocations
#       identitySources:
#         - $request.header.Authorization
#   integrations:
#     - name: aicrafts
#       authorizer: openapi-authorizer
#       authorizationTypeRoute: CUSTOM
#       sharedIntegration: true
#       integrationType: HTTP_PROXY
#       integrationUri: arn:aws:elasticloadbalancing:us-east-2:1111111:listener/app/ecsInternal-942edce/2d593801afec4f05/7c881ca25059d4b2
#       connectionType: VPC_LINK
#       integrationMethod: ANY
#       serverNameToVerify: api.dev.xxxxxx.com.br
#       # requestParameters: 
#       #   remove:header.x-pf-customer-id: ""
#       #   overwrite:header.Host: xxxxxx.dev.xxxxxx.com.br       
#       routeKey: GET /aircrafts
